(() => {
  const DEFAULTS={enabled:true,alwaysOn:true,aging:true,intensity:55,noise:32,scanlines:38,rgb:28,glitch:18,tracking:30,blur:14,color:26,agingSpeed:50};
  let settings={...DEFAULTS}, shaders, lastUrl=location.href;
  const renderers=new WeakMap();
  const getShader=n=>fetch(chrome.runtime.getURL(`shaders/${n}`)).then(r=>{if(!r.ok)throw Error(`Cannot load ${n}`);return r.text()});
  function compile(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
  class LiteRenderer {
    constructor(video,host){this.video=video;this.host=host;this.canvas=document.createElement('canvas');this.canvas.className='ytvhs-canvas';this.started=performance.now();this.dead=false;this.attach()}
    attach(){this.host.append(this.canvas);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(this.host);this.video.addEventListener('play',()=>{if(this.video.currentTime<1)this.started=performance.now()});this.video.addEventListener('seeking',()=>{if(this.video.currentTime<1)this.started=performance.now()});this.init()}
    init(){try{const gl=this.gl=this.canvas.getContext('webgl',{alpha:true,antialias:false,preserveDrawingBuffer:false,powerPreference:'low-power'});if(!gl)throw Error('WebGL unavailable');const p=gl.createProgram();gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,shaders.vertex));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,shaders.fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));this.program=p;this.pos=gl.getAttribLocation(p,'a_position');this.u=Object.fromEntries(['u_resolution','u_time','u_damage','u_intensity','u_noise','u_scan','u_rgb','u_glitch','u_track','u_blur','u_color'].map(k=>[k,gl.getUniformLocation(p,k)]));const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);this.resize();this.tick()}catch(e){console.warn('[Distortube Lite]',e);this.destroy()}}
    resize(){if(this.dead)return;const r=this.host.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1);this.canvas.width=Math.max(1,Math.round(r.width*d*.60));this.canvas.height=Math.max(1,Math.round(r.height*d*.60))}
    tick(){if(this.dead)return;const rate=document.hidden||this.video.paused?500:42;setTimeout(()=>this.tick(),rate);if(!settings.enabled){this.canvas.style.display='none';return}if(document.hidden||this.video.paused||this.video.ended)return;const gl=this.gl,now=performance.now(),age=settings.aging?Math.min(.85,(now-this.started)/(30000/Math.max(5,settings.agingSpeed))):0,u=this.u;this.canvas.style.display='block';gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(this.program);gl.uniform2f(u.u_resolution,this.canvas.width,this.canvas.height);gl.uniform1f(u.u_time,now/1000);gl.uniform1f(u.u_damage,age);gl.uniform1f(u.u_intensity,settings.intensity/100);gl.uniform1f(u.u_noise,settings.noise/100);gl.uniform1f(u.u_scan,settings.scanlines/100);gl.uniform1f(u.u_rgb,settings.rgb/100);gl.uniform1f(u.u_glitch,settings.glitch/100);gl.uniform1f(u.u_track,settings.tracking/100);gl.uniform1f(u.u_blur,settings.blur/100);gl.uniform1f(u.u_color,settings.color/100);gl.enableVertexAttribArray(this.pos);gl.vertexAttribPointer(this.pos,2,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLE_STRIP,0,4)}
    destroy(){if(this.dead)return;this.dead=true;this.observer?.disconnect();this.canvas.remove()}
  }
  function scan(){if(!shaders)return;document.querySelectorAll('video.html5-main-video, video').forEach(video=>{const host=video.closest('.html5-video-player, ytm-player, #movie_player');if(host&&!renderers.has(video))renderers.set(video,new LiteRenderer(video,host))})}
  async function start(){try{settings={...DEFAULTS,...await chrome.storage.sync.get(DEFAULTS)};const [vertex,fragment]=await Promise.all([getShader('vhs.vert.glsl'),getShader('vhs.frag.glsl')]);shaders={vertex,fragment};scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;scan()}},1000)}catch(e){console.error('[Distortube Lite]',e)}}
  chrome.storage.onChanged.addListener(changes=>{for(const [key,{newValue}] of Object.entries(changes))settings[key]=newValue});start();
})();
