(() => {
  const DEFAULTS={enabled:true,alwaysOn:true,aging:true,intensity:55,noise:32,scanlines:38,rgb:28,glitch:18,tracking:30,blur:14,color:26,agingSpeed:50};
  let settings={...DEFAULTS}, shaders, lastUrl=location.href;
  const renderers=new WeakMap();

  async function loadShaders(){
    const [vertex,fragment]=await Promise.all(['vhs.vert.glsl','vhs.frag.glsl'].map(n=>fetch(chrome.runtime.getURL('shaders/'+n)).then(r=>{if(!r.ok)throw Error('Shader unavailable');return r.text()})));
    return {vertex,fragment};
  }
  function compile(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
  class VHSRenderer {
    constructor(video,host){this.video=video;this.host=host;this.canvas=document.createElement('canvas');this.canvas.className='ytvhs-canvas';this.startedAt=0;this.lastTime=0;this.dead=false;this.attach();}
    attach(){if(!this.host)return;const style=getComputedStyle(this.host);if(style.position==='static')this.host.style.position='relative';this.host.append(this.canvas);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.host);this.video.addEventListener('play',()=>{if(this.lastTime<1)this.startedAt=performance.now()});this.video.addEventListener('seeking',()=>{if(this.video.currentTime<1){this.startedAt=performance.now();this.lastTime=0}});this.init();}
    init(){try{const gl=this.gl=this.canvas.getContext('webgl',{alpha:true,antialias:false,preserveDrawingBuffer:false,premultipliedAlpha:false})||this.canvas.getContext('experimental-webgl');if(!gl)throw Error('WebGL unavailable');const p=gl.createProgram();gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,shaders.vertex));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,shaders.fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));this.program=p;this.position=gl.getAttribLocation(p,'a_position');this.uniforms=Object.fromEntries(['u_video','u_resolution','u_time','u_damage','u_intensity','u_noise','u_scan','u_rgb','u_glitch','u_track','u_blur','u_color'].map(k=>[k,gl.getUniformLocation(p,k)]));const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);this.texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.resize();requestAnimationFrame(t=>this.draw(t));}catch(e){console.warn('[YouTube VHS]',e);this.destroy()}}
    resize(){if(this.dead)return;const r=this.host.getBoundingClientRect(), d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*d));this.canvas.height=Math.max(1,Math.round(r.height*d));}
    draw(now){if(this.dead)return;if(!this.canvas.isConnected){this.destroy();return}requestAnimationFrame(t=>this.draw(t));if(!settings.enabled){this.canvas.style.display='none';return}this.canvas.style.display='block';if(!this.video.videoWidth||this.video.paused||this.video.ended)return;try{const gl=this.gl, d=Math.min(devicePixelRatio||1,2), elapsed=this.startedAt?(now-this.startedAt)/1000:0;const age=settings.aging?Math.min(.85,elapsed/(30000/Math.max(5,settings.agingSpeed))):0;const u=this.uniforms;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(this.program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,this.video);gl.uniform1i(u.u_video,0);gl.uniform2f(u.u_resolution,this.canvas.width/d,this.canvas.height/d);gl.uniform1f(u.u_time,now/1000);gl.uniform1f(u.u_damage,age);gl.uniform1f(u.u_intensity,settings.intensity/100);gl.uniform1f(u.u_noise,settings.noise/100);gl.uniform1f(u.u_scan,settings.scanlines/100);gl.uniform1f(u.u_rgb,settings.rgb/100);gl.uniform1f(u.u_glitch,settings.glitch/100);gl.uniform1f(u.u_track,settings.tracking/100);gl.uniform1f(u.u_blur,settings.blur/100);gl.uniform1f(u.u_color,settings.color/100);gl.enableVertexAttribArray(this.position);gl.vertexAttribPointer(this.position,2,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);this.lastTime=this.video.currentTime;}catch(e){console.warn('[YouTube VHS] Video texture failed; restoring original video.',e);this.destroy()}}
    destroy(){if(this.dead)return;this.dead=true;this.resizeObserver?.disconnect();this.canvas.remove();}
  }
  function scan(){if(!shaders)return;document.querySelectorAll('video.html5-main-video, video').forEach(video=>{const host=video.closest('.html5-video-player, ytm-player, #movie_player');if(host&&!renderers.has(video))renderers.set(video,new VHSRenderer(video,host));});}
  async function start(){try{settings={...DEFAULTS,...await chrome.storage.sync.get(DEFAULTS)};shaders=await loadShaders();scan();const observer=new MutationObserver(scan);observer.observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;scan()}},500);}catch(e){console.error('[YouTube VHS] Unable to start',e)}}
  chrome.storage.onChanged.addListener(changes=>{for(const [key,{newValue}] of Object.entries(changes))settings[key]=newValue});
  start();
})();
